import type { Metadata } from "next";
import { Bellefair, Barlow } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const bellefair = Bellefair({
  variable: "--font-bellefair",
  weight: ["400"],
  subsets: ["latin"],
});

const barlow = Barlow({
  variable: "--font-barlow",
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bellefair.variable} ${barlow.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
